### ISSUE TITLE
Request to add a licence

### ISSUE THREAD

**Issue by musab-k** [chasdevs/meetrics#2]
Hi,

Thanks for creating this project, I'm looking to do something similar at my company. Would you be willing to please add a licence to it so I can do so (https://choosealicense.com/no-permission/)?

Thanks!

**Comment by chasdevs** [comment]
Glad you have a use-case! I'm going to hold off on licensing for the moment; I'm actually trying to turn a version of this into a product so I don't want to open it up for distribution just yet. Go ahead and use it for your work and such. Combining this with something like https://www.metabase.com/ makes it easy to create charts for your company.
