### ISSUE TITLE
Docker can't read config/development.yml 

### ISSUE THREAD

**Issue by Akibalogh** [chasdevs/meetrics#3]
aki-macbook-pro:meetrics akibalogh$ docker run --rm -e DB_HOST="docker.for.mac.localhost" chasdevs/meetrics
time="2020-04-08T21:59:27Z" level=info msg="Environment: development\n"
time="2020-04-08T21:59:27Z" level=error msg="Error reading config file. Check to make sure the config/development.yml file exists."
panic: open /app/config/development.yml: no such file or directory

goroutine 1 [running]:
github.com/chasdevs/meetrics/pkg/conf.init.0()
	/app/pkg/conf/conf.go:27 +0x2db

**Comment by Akibalogh** [comment]
I hardcoded the link in pkg/conf/conf.go and got the same error

**Comment by chasdevs** [comment]
Ah, try mounting your local directory: ```docker run --rm -e DB_HOST="host.docker.internal" -v `pwd`:/app chasdevs/meetrics```

**Comment by Akibalogh** [comment]
Thank you!

Sorry, I realize you're not docker support :D but do you have any ideas on why I'm getting this?
```
aki-macbook-pro:meetrics akibalogh$ docker run --rm -e DB_HOST="host.docker.internal" -v `pwd`:/app chasdevs/meetrics
docker: Error response from daemon: Mounts denied:
The path /var/www/apps/meetrics
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled
```

![Screen Shot 2020-04-09 at 3 58 28 PM](https://user-images.githubusercontent.com/588227/78935562-f9934b00-7a7a-11ea-9e45-b33cd36bcd8b.png)

My guess is it's something to do with the fact that the path is /private/var/... in OSX but I haven't figured out how to fix it

**Comment by chasdevs** [comment]
Ha no problem; docker can be tricky. Looks like the current repository is `/var/www/apps`, but you had `/private/var/www/apps` green-lit in your docker settings.

Usually I'll just checkout my git repos into something like a `/Users/chasdevs/Code/...` folder; your /Users directory should be mountable to docker containers. I think /var/www/ is generally more for local apache-hosted PHP sites and things like that.

**Comment by Akibalogh** [comment]
Thank you, that makes sense. Yes, I'm lazy (more of just a hobbyist/cowboy coder) so I put my apps in that directory a long time ago to save coding/config time on something else (haha). This is an easy fix tho. Appreciate it! Worked, closing..
